package ch.LFG.repository;

import ch.LFG.entity.Group;
import org.springframework.data.jpa.repository.JpaRepository;

public interface GroupRepository extends JpaRepository<Group, Long> {
    //Find, Update, Save, Delete, and others get generated by the interface we extend
}

