package ch.LFG.repository;

import ch.LFG.entity.GroupProfil;
import org.springframework.data.jpa.repository.JpaRepository;

public interface GroupProfilRepository extends JpaRepository<GroupProfil, Long> {
    //Find, Update, Save, Delete, and others get generated by the interface we extend
}

