package ch.LFG.repository;

import ch.LFG.entity.Match;
import org.springframework.data.jpa.repository.JpaRepository;

public interface MatchRepository extends JpaRepository<Match, Long> { //Integer
    //Find, Update, Save, Delete, and others get generated by the interface we extend
}
