package ch.LFG.repository;

import ch.LFG.entity.UserProfil;
import org.springframework.data.jpa.repository.JpaRepository;

public interface UserProfilRepository extends JpaRepository<UserProfil, Long> { //Integer
    //Find, Update, Save, Delete, and others get generated by the interface we extend
}

